export default function Head() {
  return (
    <>
      <title>ZenS</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"
      />
      <link rel="icon" href="/Logo.svg" />
    </>
  );
}
